method: grid
metric: 
  goal : maximize 
  name : avg_total_reward
parameters :
  gamma:
    values : [0.99]
  epochs :
    values : [1000000]
  env_id:
    values : ["BreakoutNoFrameskip-v4"]
  capture_video :
    values : [False]
  total_timesteps :
    values : [50000000]
  learning_rate :
    values : [0.00025]
  num_envs :
    values : [1]
  buffer_size :
    values : [1000000]
  tau :
    values : [0.9]
  target_network_frequency :
    values : [5000]
  batch_size :
    values : [256]
  epsilon_a :
    values : [1.0]
  epsilon_b :
    values : [0.1]
  exploration_fraction :
    values : [0.10]
  step_start_learning :
    values : [10000]
  training_frequency :
    values : [2]
  seed :
    values : [988, 10, 23]
  