method: grid
metric: 
  goal : maximize 
  name : avg_total_reward
parameters :
  gamma:
    values : [0.99]
  env_id:
    values : ["BreakoutNoFrameskip-v4"]
  capture_video :
    values : [False]
  total_timesteps :
    values : [100000]
  learning_rate :
    values : [0.001]
  num_envs :
    values : [1]
  buffer_size :
    values : [1000000]
  tau :
    values : [0.9]
  k :
    values : [1, 3, 6, 10]
  epochs :
    values : [50000]
  evaluation_epochs :
    values : [10000]
  target_network_frequency :
    values : [50]
  batch_size :
    values : [128]
  epsilon_a :
    values : [1.0]
  epsilon_b :
    values : [0.01]
  exploration_fraction :
    values : [0.10]
  step_start_learning :
    values : [100]
  training_frequency :
    values : [4]
  seed :
    values : [43]
  